Import of links-2.1pre26

diff --git a/links/user/links/rebuild b/links/user/links/rebuild
--- a/links/user/links/rebuild
+++ b/links/user/links/rebuild
@@ -3,6 +3,67 @@
 # (c) 2002 Karel 'Clock' Kulhavy, Mikulas Patocka, Petr 'Brain' Kulhavy
 # This file is a part of the Links program, released under GPL.
 
+make=make
+if which gmake 2>/dev/null >/dev/null && gmake --version | grep -i "GNU Make" >/dev/null
+then
+echo Found GNU Make under gmake. Going to use gmake instead of make.
+make=gmake
+fi
+
+if which autoheader-2.13 2>/dev/null >/dev/null
+then
+autoheader="autoheader-2.13"
+else
+autoheader="autoheader"
+fi
+
+if [ "$1" = reconf ]; then
+	if ! which pkg-config 2>/dev/null >/dev/null
+	then
+	echo Warning: You don\'t have pkg-config. The PKG_CHECK_MODULES macro will probably fail. >&2	
+	fi
+
+	if ! which autoconf 2>/dev/null >/dev/null
+	then
+		echo You don\'t have autoconf. Wiping out. >&2
+		exit 1
+	fi
+
+	if ! autoconf --version | grep -i "GNU Autoconf" >/dev/null
+	then
+		echo This looks like autoconf installed on OpenBSD. >&2
+		if ! AUTOCONF_VERSION=2.13 autoconf --version 2>/dev/null >/dev/null
+		then
+			echo Autoconf 2.13 is not found. This script needs at most autoconf 2.13. \
+			Trying with some other \(random\) autoconf. >&2
+			path=`echo "$PATH" | tr -s ':' '\n'`
+			alt=`find $path -name 'autoconf*' -and ! -name autoconf | head -n 1`
+			if [ -z "$alt" ]
+				then
+				echo Cannot find the real autoconf >&2
+				exit 1
+			fi
+			export AUTOCONF_VERSION=`echo $alt | sed -e 's/^.*autoconf-//g'`
+			echo Found $alt. Setting AUTOCONF_VERSION to $AUTOCONF_VERSION.>&2
+		else
+			echo Found Autoconf 2.13. It should work. >&2
+			export AUTOCONF_VERSION=2.13
+		fi
+	fi
+
+	if ! automake --version | grep -i "GNU automake" >/dev/null
+	then
+		echo This looks like automake installed on OpenBSD. >&2
+		export AUTOMAKE_VERSION=1.4
+		if ! automake --version 2>/dev/null >/dev/null
+		then
+			echo Automake 1.4 is needed. Wiping out. >&2
+			exit 1
+		fi
+		echo Found Automake 1.4. It should work. >&2
+	fi
+fi
+
 rm -f config.h Makefile config.cache &&
 if [ "$1" = reconf ]; then
 	echo NEPOUZIVAT pokud nebylo zmeneno configure.in nebo Makefile.am !!! &&
@@ -16,7 +77,7 @@ if [ "$1" = reconf ]; then
 		echo Zodpovednost prijata. &&
 		echo Responsibility accepted. &&
 		rm -rf .deps missing depcomp aclocal.m4 &&
-		autoheader &&
+		$autoheader &&
 		rm -f autoh* &&
 		aclocal &&
 		automake --add-missing &&
@@ -38,10 +99,10 @@ export CFLAGS="$CFLAGS -Wall -g -O2 -pipe -ansi -U__STRICT_ANSI__ -fno-common" &
 #export CFLAGS="-Wall -g -O2 -pipe"
 export CXXFLAGS="$CXXFLAGS -Wall -g -O2 -pipe" &&
 ./configure --enable-graphics --enable-javascript &&
-make clean &&
-make &&
+$make clean &&
+$make &&
 if [ "$1" = reconf ]; then
-	autoheader &&
+	$autoheader &&
 	automake --add-missing --include-deps --build-dir=. --srcdir-name=. --output-dir=. &&
 	sed 's%sed '\''s/\\\.am\$/\.in/'\''%sed '\''s/\\\.[aA][mM]\$/\.in/'\''%' <missing >missing.tmp &&
 	mv -f missing.tmp missing &&
